server:
  port: 8888
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/small?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456